# Generated by Django 5.1.6 on 2025-05-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_description_invoice_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارت بانکی'), ('transfer', 'انتقال بانکی'), ('other', 'سایر')], default='cash', max_length=20, verbose_name='روش پرداخت'),
        ),
    ]
