# Generated by Django 5.1.6 on 2025-05-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_payment_date_invoice_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='payment_date',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_paid',
            field=models.BooleanField(default=True, verbose_name='پرداخت شده؟'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدی'), ('card', 'پرداخت با پوز')], default='cash', max_length=20, verbose_name='روش پرداخت'),
        ),
    ]
