# Generated by Django 5.2 on 2025-05-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_remove_invoice_payment_date_alter_invoice_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='receipt_image',
            field=models.ImageField(blank=True, help_text='فقط برای پرداخت\u200cهای کارتی الزامی است', null=True, upload_to='receipts/%Y/%m/%d/', verbose_name='عکس فیش واریزی'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارت')], default='cash', max_length=20, verbose_name='روش پرداخت'),
        ),
    ]
