# Generated by Django 5.2 on 2025-05-10 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_invoice_receipt_image_alter_invoice_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at'], 'permissions': [('view_dashboard', 'Can view dashboard')], 'verbose_name': 'فاکتور', 'verbose_name_plural': 'فاکتورها'},
        ),
    ]
