# Generated by Django 5.2 on 2025-10-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_alter_invoice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pos_card_mask',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='کارت (ماسک)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pos_date',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='تاریخ تراکنش (خام)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pos_merchant',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='پذیرنده'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pos_provider',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='پوز'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pos_rrn',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='شماره پیگیری (RRN)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pos_terminal',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='ترمینال'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pos_trace',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='شماره پیگیری داخلی (Trace)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pos_txn_status',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='کد وضعیت تراکنش'),
        ),
    ]
