# Generated by Django 5.2 on 2025-10-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_invoice_pos_card_mask_invoice_pos_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده؟'),
        ),
    ]
