# Generated by Django 5.1.6 on 2025-05-05 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام غرفه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('image', models.ImageField(blank=True, null=True, upload_to='booths/', verbose_name='تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booths', to='events.event', verbose_name='رویداد')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_booths', to=settings.AUTH_USER_MODEL, verbose_name='مدیر غرفه')),
                ('staff', models.ManyToManyField(blank=True, related_name='booth_staff', to=settings.AUTH_USER_MODEL, verbose_name='کارکنان غرفه')),
            ],
            options={
                'verbose_name': 'غرفه',
                'verbose_name_plural': 'غرفه\u200cها',
                'ordering': ['name'],
            },
        ),
    ]
