# Generated by Django 5.1.6 on 2025-05-06 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دستگاه')),
                ('device_type', models.CharField(choices=[('VERIFONE_VX520', 'Verifone VX520'), ('PAXS80', 'PAX S80'), ('INKING910', 'Inking 910'), ('OTHER', 'سایر')], default='VERIFONE_VX520', max_length=20, verbose_name='نوع دستگاه')),
                ('connection_type', models.CharField(choices=[('TCP', 'TCP/IP'), ('SERIAL', 'پورت سریال'), ('USB', 'USB')], default='TCP', max_length=10, verbose_name='نوع اتصال')),
                ('bank', models.CharField(choices=[('SAMAN', 'سامان'), ('MELLAT', 'ملت'), ('PARSIAN', 'پارسیان'), ('MELLI', 'ملی'), ('OTHER', 'سایر')], default='SAMAN', max_length=10, verbose_name='بانک')),
                ('ip_address', models.CharField(blank=True, max_length=15, null=True, verbose_name='آدرس IP')),
                ('port', models.PositiveIntegerField(blank=True, default=8583, null=True, verbose_name='پورت')),
                ('serial_port', models.CharField(blank=True, help_text='مثال: COM1', max_length=20, null=True, verbose_name='پورت سریال')),
                ('baud_rate', models.PositiveIntegerField(blank=True, default=9600, null=True, verbose_name='نرخ باد')),
                ('terminal_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='شناسه ترمینال')),
                ('merchant_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='شناسه پذیرنده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_devices', to='booths.booth', verbose_name='غرفه')),
            ],
            options={
                'verbose_name': 'دستگاه پوز',
                'verbose_name_plural': 'دستگاه\u200cهای پوز',
            },
        ),
    ]
