# Generated by Django 5.2 on 2025-10-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0002_posdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='posdevice',
            name='is_kiosk',
            field=models.BooleanField(default=False, verbose_name='برای کیوسک؟'),
        ),
        migrations.AlterField(
            model_name='posdevice',
            name='bank',
            field=models.CharField(choices=[('SAMAN', 'سامان'), ('MELLAT', 'ملت'), ('PARSIAN', 'پارسیان'), ('PASARGAD', 'پاسارگاد'), ('MELLI', 'ملی'), ('OTHER', 'سایر')], default='SAMAN', max_length=10, verbose_name='بانک'),
        ),
    ]
