# Generated by Django 5.2 on 2025-10-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0003_posdevice_is_kiosk_alter_posdevice_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posdevice',
            name='device_type',
            field=models.CharField(choices=[('VERIFONE_VX520', 'Verifone VX520'), ('PAXS80', 'PAX S80'), ('INKING910', 'Inking 910'), ('AMP9200', 'AMP 9200'), ('OTHER', 'سایر')], default='VERIFONE_VX520', max_length=20, verbose_name='نوع دستگاه'),
        ),
    ]
