# Generated by Django 5.2 on 2025-10-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0004_alter_posdevice_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='show_in_kiosk',
            field=models.BooleanField(default=True, verbose_name='نمایش داخل کیوسک'),
        ),
    ]
