# Generated by Django 5.2 on 2025-10-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0005_booth_show_in_kiosk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='show_in_kiosk',
            field=models.BooleanField(default=False, verbose_name='نمایش داخل کیوسک'),
        ),
    ]
