"""
Django settings for charity_event_manager project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured("The SECRET_KEY environment variable is not set.")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() in ['true', '1', 'yes']

ALLOWED_HOSTS = ['*']  # Allow all hosts for local network access


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',  # اضافه کردن ماژول humanize برای فیلترهای نمایش انسان‌پسند اعداد و تاریخ‌ها
    
    # Third-party apps
    'crispy_forms',
    'crispy_bootstrap5',
    'rest_framework',
    'corsheaders',
    
    # Local apps
    'events',
    'booths',
    'products',
    'invoices',
    'settings_app',  # اپلیکیشن تنظیمات و آپلود فونت
    'reports',  # اپلیکیشن گزارشات
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Add CORS middleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'charity_event_manager.middleware.AccessControlMiddleware',  # اضافه کردن میان‌افزار کنترل دسترسی
]

ROOT_URLCONF = 'charity_event_manager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Add templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'charity_event_manager.context_processors.app_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'charity_event_manager.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # ابتدا از SQLite استفاده می‌کنیم برای سادگی توسعه
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# در آینده می‌توانید به PostgreSQL مهاجرت کنید:
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'charity_event_db',
        'USER': 'postgres',
        'PASSWORD': 'your_password',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}
"""


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fa-ir'  # تغییر به فارسی

TIME_ZONE = 'Asia/Tehran'  # تغییر به منطقه زمانی ایران

USE_I18N = True

# فعال کردن بومی‌سازی (فرمت اعداد، تاریخ‌ها و غیره)
USE_L10N = True

# تنظیمات مربوط به فرمت اعداد فارسی
NUMBER_GROUPING = 3  # جداکننده هر سه رقم
THOUSAND_SEPARATOR = ','  # جداکننده کاما
DECIMAL_SEPARATOR = '.'  # جداکننده اعشاری

USE_TZ = True

# POS Bridge defaults (can be overridden via environment or local settings)
POS_BRIDGE_URL = os.environ.get('POS_BRIDGE_URL', 'http://127.0.0.1:7070')
POS_TEST_MODE = os.environ.get('POS_TEST_MODE', 'false').lower() in ['1', 'true', 'yes']


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# تنظیمات سفارشی برنامه
DASHBOARD_REFRESH_INTERVAL = 10  # زمان به‌روزرسانی داشبورد به ثانیه

# تنظیمات crispy forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# CORS settings for mobile app
CORS_ALLOW_ALL_ORIGINS = True  # در محیط توسعه اجازه دسترسی به همه مبدأها را می‌دهیم
# در محیط تولید این مقدار را برای امنیت بیشتر محدود کنید
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:8000",
#     "http://127.0.0.1:8000",
# ]

# Login and logout URLs
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# POS (Pasargad) defaults for kiosk; will be overridden by UI-config later
POS_IP = os.environ.get('POS_IP', '192.168.1.8')
POS_PORT = int(os.environ.get('POS_PORT', '7000'))
POS_TIMEOUT_MS = int(os.environ.get('POS_TIMEOUT_MS', '60000'))
POS_DEBUG = os.environ.get('POS_DEBUG', 'false').lower() in ['1', 'true', 'yes']

# Kiosk settings
KIOSK_INACTIVITY_SECONDS = int(os.environ.get('KIOSK_INACTIVITY_SECONDS', '60'))

# Unauthenticated auto-redirect to kiosk after N seconds
KIOSK_REDIRECT_SECONDS = int(os.environ.get('KIOSK_REDIRECT_SECONDS', '30'))

# Invoices list incremental polling interval (seconds)
INVOICE_LIST_POLL_SECONDS = int(os.environ.get('INVOICE_LIST_POLL_SECONDS', '10'))

# POS visibility: hide kiosk-selected POS from its booth lists
HIDE_KIOSK_POS_IN_BOOTH = os.environ.get('HIDE_KIOSK_POS_IN_BOOTH', 'true').lower() in ['1', 'true', 'yes']

# Nobat TTS (voice) settings
# Enable/disable TTS generation for Nobat page announcements
NOBAT_TTS_ENABLED = os.environ.get('NOBAT_TTS_ENABLED', 'true').lower() in ['1', 'true', 'yes']
# Backend: 'espeak' (رایگان و آفلاین)، 'azure' (ابری)، 'browser' (Web Speech API)، یا 'off'
NOBAT_TTS_BACKEND = os.environ.get('NOBAT_TTS_BACKEND', 'espeak').lower()
# Language code for gTTS
NOBAT_TTS_LANG = os.environ.get('NOBAT_TTS_LANG', 'fa')
# Optional: delete audio files older than N days on each generation (0 to disable)
NOBAT_TTS_CLEANUP_DAYS = int(os.environ.get('NBAT_TTS_CLEANUP_DAYS', '0'))
# Azure Speech credentials (required if NOBAT_TTS_BACKEND='azure')
AZURE_SPEECH_KEY = os.environ.get('AZURE_SPEECH_KEY')
AZURE_SPEECH_REGION = os.environ.get('AZURE_SPEECH_REGION')

# eSpeak NG options (only for backend='espeak')
NOBAT_TTS_ESPEAK_VOICE = os.environ.get('NOBAT_TTS_ESPEAK_VOICE', 'fa')
NOBAT_TTS_ESPEAK_RATE = int(os.environ.get('NOBAT_TTS_ESPEAK_RATE', '150'))  # کلمات در دقیقه
NOBAT_TTS_USE_FFMPEG = os.environ.get('NOBAT_TTS_USE_FFMPEG', 'true').lower() in ['1','true','yes']  # تبدیل WAV به MP3 در صورت وجود ffmpeg

