# Generated by Django 6.0.5 on 2026-05-29 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booths', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='شماره فاکتور')),
                ('customer_name', models.CharField(max_length=255, verbose_name='نام مشتری')),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره موبایل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('donation_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مبلغ همت عالی')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مبلغ تخفیف')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مبلغ کل')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده؟')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارت')], default='cash', max_length=20, verbose_name='روش پرداخت')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/%d/', verbose_name='عکس فیش واریزی')),
                ('pos_provider', models.CharField(blank=True, max_length=50, null=True, verbose_name='پوز')),
                ('pos_rrn', models.CharField(blank=True, max_length=32, null=True, verbose_name='شماره پیگیری (RRN)')),
                ('pos_trace', models.CharField(blank=True, max_length=32, null=True, verbose_name='شماره پیگیری داخلی (Trace)')),
                ('pos_txn_status', models.CharField(blank=True, max_length=8, null=True, verbose_name='کد وضعیت تراکنش')),
                ('pos_terminal', models.CharField(blank=True, max_length=32, null=True, verbose_name='ترمینال')),
                ('pos_merchant', models.CharField(blank=True, max_length=64, null=True, verbose_name='پذیرنده')),
                ('pos_card_mask', models.CharField(blank=True, max_length=64, null=True, verbose_name='کارت (ماسک)')),
                ('pos_date', models.CharField(blank=True, max_length=32, null=True, verbose_name='تاریخ تراکنش (خام)')),
                ('is_ready', models.BooleanField(default=False, verbose_name='آماده تحویل؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='booths.booth', verbose_name='غرفه')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت واحد')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='تحویل شده؟')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice', verbose_name='فاکتور')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'آیتم فاکتور',
                'verbose_name_plural': 'آیتم\u200cهای فاکتور',
            },
        ),
    ]
