# Generated by Django 5.2.15 on 2026-06-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={
                "ordering": ["-created_at"],
                "permissions": [("view_dashboard", "Can view dashboard")],
                "verbose_name": "فاکتور",
                "verbose_name_plural": "فاکتورها",
            },
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="is_ready",
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="receipt_image",
            field=models.ImageField(
                blank=True,
                help_text="فقط برای پرداخت\u200cهای کارتی الزامی است",
                null=True,
                upload_to="receipts/%Y/%m/%d/",
                verbose_name="عکس فیش واریزی",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
