# Generated by Django 6.0.5 on 2026-05-29 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام غرفه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('image', models.ImageField(blank=True, null=True, upload_to='booths/', verbose_name='تصویر')),
                ('show_in_kiosk', models.BooleanField(default=False, verbose_name='نمایش داخل کیوسک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booths', to='events.event', verbose_name='رویداد')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_booths', to=settings.AUTH_USER_MODEL, verbose_name='مدیر غرفه')),
                ('staff', models.ManyToManyField(blank=True, related_name='booth_staff', to=settings.AUTH_USER_MODEL, verbose_name='کارکنان غرفه')),
            ],
            options={
                'verbose_name': 'غرفه',
                'verbose_name_plural': 'غرفه\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='POSDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دستگاه')),
                ('device_type', models.CharField(choices=[('VERIFONE_VX520', 'Verifone VX520'), ('PAXS80', 'PAX S80'), ('INKING910', 'Inking 910'), ('AMP9200', 'AMP 9200'), ('OTHER', 'سایر')], default='VERIFONE_VX520', max_length=20, verbose_name='نوع دستگاه')),
                ('connection_type', models.CharField(choices=[('TCP', 'TCP/IP'), ('SERIAL', 'پورت سریال'), ('USB', 'USB')], default='TCP', max_length=10, verbose_name='نوع اتصال')),
                ('bank', models.CharField(choices=[('SAMAN', 'سامان'), ('MELLAT', 'ملت'), ('PARSIAN', 'پارسیان'), ('PASARGAD', 'پاسارگاد'), ('MELLI', 'ملی'), ('OTHER', 'سایر')], default='SAMAN', max_length=10, verbose_name='بانک')),
                ('ip_address', models.CharField(blank=True, max_length=15, null=True, verbose_name='آدرس IP')),
                ('port', models.PositiveIntegerField(blank=True, default=8583, null=True, verbose_name='پورت')),
                ('serial_port', models.CharField(blank=True, help_text='مثال: COM1', max_length=20, null=True, verbose_name='پورت سریال')),
                ('baud_rate', models.PositiveIntegerField(blank=True, default=9600, null=True, verbose_name='نرخ باد')),
                ('terminal_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='شناسه ترمینال')),
                ('merchant_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='شناسه پذیرنده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('is_kiosk', models.BooleanField(default=False, verbose_name='برای کیوسک؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_devices', to='booths.booth', verbose_name='غرفه')),
            ],
            options={
                'verbose_name': 'دستگاه پوز',
                'verbose_name_plural': 'دستگاه\u200cهای پوز',
            },
        ),
    ]
