# Generated by Django 5.2.15 on 2026-06-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booths", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booth",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="posdevice",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
