# Generated by Django 5.2.15 on 2026-06-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booths", "0002_alter_booth_id_alter_posdevice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booth",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="posdevice",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
