# Generated by Django 5.1.6 on 2025-05-05 16:47

import django.db.models.deletion
import settings_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام فونت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('font_file', models.FileField(help_text='فایل فونت باید در فرمت TTF یا WOFF باشد', upload_to=settings_app.models.font_file_path, verbose_name='فایل فونت')),
                ('font_type', models.CharField(choices=[('primary', 'فونت اصلی'), ('secondary', 'فونت ثانویه'), ('heading', 'عناوین')], default='primary', max_length=20, verbose_name='نوع فونت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'فونت',
                'verbose_name_plural': 'فونت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='سیستم مدیریت رویدادهای خیریه', max_length=100, verbose_name='عنوان سایت')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='لوگو')),
                ('primary_color', models.CharField(default='#0d6efd', max_length=20, verbose_name='رنگ اصلی')),
                ('secondary_color', models.CharField(default='#6c757d', max_length=20, verbose_name='رنگ ثانویه')),
                ('primary_font', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_settings', to='settings_app.font', verbose_name='فونت اصلی')),
            ],
            options={
                'verbose_name': 'تنظیمات سیستم',
                'verbose_name_plural': 'تنظیمات سیستم',
            },
        ),
    ]
