# Generated by Django 5.1.6 on 2025-05-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='items_per_page',
            field=models.IntegerField(default=20, help_text='تعداد آیتم\u200cهایی که در هر صفحه از لیست\u200cها نمایش داده می\u200cشود (بین 10 تا 100)', verbose_name='تعداد آیتم در هر صفحه'),
        ),
    ]
